### ISSUE TITLE
Build API documentation

### ISSUE THREAD

**Issue by GeoZac** [GeoZac/unconv_spring#188]
Ref: https://spring.io/projects/spring-restdocs

- [x] Add dependecies to POM (#251)
- [x] Keep base docs in source (#251)
- [x] Generate API docs on Controllertests (#251)
